name: On push (tests, build)
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.16'
          registry-url: 'https://registry.npmjs.org'
      - run: npm i
      - run: npm test

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.16'
          registry-url: 'https://registry.npmjs.org'
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action (no need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # this action will not release
          release: false
